# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Datum')),
                ('place', models.CharField(max_length=100, verbose_name='Kraj')),
                ('offer_number', models.PositiveIntegerField(editable=False, verbose_name='Predračun')),
                ('tickets', models.IntegerField(verbose_name='Karta - 30$')),
                ('cd', models.IntegerField(verbose_name='CD - 15$')),
                ('total_no_vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Znesek brez DDV')),
                ('total_with_vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Znesek z DDV')),
                ('payed', models.BooleanField(default=False, verbose_name='Plačano')),
                ('pay_until', models.DateField(editable=False, null=True, verbose_name='Rok plačila')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Prejemnik')),
            ],
            options={
                'verbose_name_plural': 'predračuni',
                'verbose_name': 'predračun',
            },
        ),
    ]
